[package]
name = "hoist-isle-compiler"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "isle-compile"
path = "build_support/isle_compile.rs"

[dependencies]
cranelift-isle = { path = "../wasmtime/cranelift/isle/isle" }
